print("HTTP/1.1 404 Not Found")
print ("server: web")
print("Content-Type: text/html")
print("")
print("<html>")
print("        <head>")
print("                <title>may site</title>")
print("        </head>")
print("        <body>")
print("                <h1>web serv<br>exist</h1>")
print("        </body>")
print("</html>")
